
    
version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

  mqttbridge:
    build: ./mqtt-sensor-bridge
    image: bluerobot/mqttbridge
    container_name: mqttbridge
    depends_on:
      - influxdb
    restart: always