{
 "title": "Blue PI Sensors",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SHOW TAG VALUES ON \"telegraf\" FROM \"Blue_pi_sensors\" WITH KEY = \"IoTHubDeviceConnectionID\""
   },
   {
    "name": "Environment",
    "query": "show field keys on telegraf from Blue_env_sensor "
   }
  ]
 },
 "panels": [
  {
   "title": "$Environment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "Environment",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Blue_env_sensor",
     "query": "SELECT mean(/^$Environment$/) FROM \"Blue_env_sensor\" WHERE (\"IoTHubDeviceConnectionID\" =~ /^$Device$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "/^$Environment$/" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Blue_env_sensor",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Blue_env_sensor",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Blue_env_sensor",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "IMU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gyro",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "rad / s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "gyro_x" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "x" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "gyro_y" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "y" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "gyro_z" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "z" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      }
     ]
    },
    {
     "title": "Accellerometer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "accG" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "acc_x" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "acc_y" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "acc_z" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      }
     ]
    },
    {
     "title": "Orientation",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "orientation_pitch" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "orientation_roll" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_imu_sensor",
       "select": [
        [
         { "params": [ "orientation_yaw" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Humidity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_env_sensor",
       "select": [
        [
         { "params": [ "humidity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "humidity" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "Blue_env_sensor",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "pressurembar" }
     ],
     "targets": [
      {
       "alias": "Pressure",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Blue_env_sensor",
       "select": [
        [
         { "params": [ "pressure" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "IoTHubDeviceConnectionID", "operator": "=~", "value": "/^$Device$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}